theme = "lynx"
title = "Bateria Alcalina"


enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Bateria Alcalina"
  headline = "19 anos sem menisquÃªncia ğŸ¥ğŸ’šğŸ–¤ğŸ’›â¤"
  image = "alcalina.png"
  links = [
    { facebook = "https://www.facebook.com/bateriaalcalinacps" },
    { instagram = "https://www.instagram.com/bateriaalcalina/" },
    { youtube = "https://www.youtube.com/@bateriaalcalina1056" },
    { soundcloud = "https://soundcloud.com/bateriaalcalina" },
  ]

[params]
attribution = false

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true