theme = "lynx"
title = "Bateria Alcalina"


enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Bateria Alcalina"
  headline = "Desde 2003 sem menisquÃªncia ğŸ¥ğŸ’šğŸ–¤ğŸ’›â¤"
  image = "alcalina.png"
  links = [
    { facebook = "https://www.facebook.com/bateriaalcalinacps" },
    { instagram = "https://www.instagram.com/bateriaalcalina/" },
    { youtube = "https://www.youtube.com/@bateriaalcalina1056" },
    { soundcloud = "https://soundcloud.com/bateriaalcalina" },
    { feijoada = { href = "https://forms.gle/8jag3uwQp99jjA3a6", text = "Feijoada Altaneira 2025", icon = "link" } },
  ]

[params]
attribution = false

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
